name: Linux Package
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mangosd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for Submodule Updates
        run: source ./apps/ci/ci-submodule-update.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-mangosd
        uses: docker/metadata-action@v5
        with:
          images: dongstech/mangoszero-mangosd
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image mangosd
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockercontainer/DockerFile-mangosd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-mangosd.outputs.tags }}
          labels: ${{ steps.meta-mangosd.outputs.labels }}

  realmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for Submodule Updates
        run: source ./apps/ci/ci-submodule-update.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-realmd
        uses: docker/metadata-action@v5
        with:
          images: dongstech/mangoszero-realmd
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image realmd
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockercontainer/DockerFile-realmd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-realmd.outputs.tags }}
          labels: ${{ steps.meta-realmd.outputs.labels }}