name: Linux Package
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_APPID }}
      ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_SUBSCRIPTION_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Check for Submodule Updates
        run: source ./apps/ci/ci-submodule-update.sh

      - name: Log into Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-mangosd
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: dongstech/mangoszero-mangosd

      - name: Build and push Docker image mangosd
        working-directory: ./dockercontainer
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile-mangosd
          push: true
          tags: ${{ steps.meta-mangosd.outputs.tags }}
          labels: ${{ steps.meta-mangosd.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-realmd
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: dongstech/mangoszero-realmd

      - name: Build and push Docker image realmd
        working-directory: ./dockercontainer
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile-realmd
          push: true
          tags: ${{ steps.meta-realmd.outputs.tags }}
          labels: ${{ steps.meta-realmd.outputs.labels }}